# Generated by Django 2.2.7 on 2019-12-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maplot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Longitude',
            new_name='longitude',
        ),
    ]
